import type { Employee } from "@/types";
import type { AttendanceRecord, LeaveRequest } from "@/stores/attendance-store";
import type { PayrollRecord } from "@/types";
import type {
  DashboardStats,
  AttendanceTrend,
  DepartmentDistribution,
  RecentActivity,
} from "@/hooks/use-dashboard";

export const departments = [
  "Engineering",
  "Human Resources",
  "Marketing",
  "Sales",
  "Finance",
  "Operations",
  "Design",
  "Customer Support",
];

export const mockEmployees: Employee[] = [
  {
    id: "1",
    employeeId: "EMP001",
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah.johnson@hrflow.com",
    phone: "+1 555-0101",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    department: "Engineering",
    position: "Senior Software Engineer",
    employmentType: "full_time",
    status: "active",
    hireDate: "2021-03-15",
    salary: 95000,
    managerId: "5",
    address: "123 Tech Street, San Francisco, CA 94102",
    emergencyContact: { name: "John Johnson", phone: "+1 555-0102", relationship: "Spouse" },
    createdAt: "2021-03-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "2",
    employeeId: "EMP002",
    firstName: "Michael",
    lastName: "Chen",
    email: "michael.chen@hrflow.com",
    phone: "+1 555-0103",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
    department: "Design",
    position: "UI/UX Designer",
    employmentType: "full_time",
    status: "active",
    hireDate: "2022-01-10",
    salary: 85000,
    managerId: "5",
    createdAt: "2022-01-10T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "3",
    employeeId: "EMP003",
    firstName: "Emily",
    lastName: "Rodriguez",
    email: "emily.rodriguez@hrflow.com",
    phone: "+1 555-0104",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily",
    department: "Human Resources",
    position: "HR Manager",
    employmentType: "full_time",
    status: "active",
    hireDate: "2020-06-20",
    salary: 78000,
    createdAt: "2020-06-20T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "4",
    employeeId: "EMP004",
    firstName: "James",
    lastName: "Williams",
    email: "james.williams@hrflow.com",
    phone: "+1 555-0105",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=James",
    department: "Sales",
    position: "Sales Representative",
    employmentType: "full_time",
    status: "active",
    hireDate: "2023-02-28",
    salary: 62000,
    managerId: "7",
    createdAt: "2023-02-28T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "5",
    employeeId: "EMP005",
    firstName: "Amanda",
    lastName: "Taylor",
    email: "amanda.taylor@hrflow.com",
    phone: "+1 555-0106",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amanda",
    department: "Engineering",
    position: "Engineering Manager",
    employmentType: "full_time",
    status: "active",
    hireDate: "2019-09-01",
    salary: 125000,
    createdAt: "2019-09-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "6",
    employeeId: "EMP006",
    firstName: "David",
    lastName: "Brown",
    email: "david.brown@hrflow.com",
    phone: "+1 555-0107",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=David",
    department: "Finance",
    position: "Financial Analyst",
    employmentType: "full_time",
    status: "on_leave",
    hireDate: "2021-11-15",
    salary: 72000,
    createdAt: "2021-11-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "7",
    employeeId: "EMP007",
    firstName: "Jennifer",
    lastName: "Martinez",
    email: "jennifer.martinez@hrflow.com",
    phone: "+1 555-0108",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jennifer",
    department: "Sales",
    position: "Sales Manager",
    employmentType: "full_time",
    status: "active",
    hireDate: "2020-04-12",
    salary: 98000,
    createdAt: "2020-04-12T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "8",
    employeeId: "EMP008",
    firstName: "Robert",
    lastName: "Garcia",
    email: "robert.garcia@hrflow.com",
    phone: "+1 555-0109",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Robert",
    department: "Marketing",
    position: "Marketing Specialist",
    employmentType: "full_time",
    status: "active",
    hireDate: "2022-07-01",
    salary: 65000,
    createdAt: "2022-07-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "9",
    employeeId: "EMP009",
    firstName: "Lisa",
    lastName: "Anderson",
    email: "lisa.anderson@hrflow.com",
    phone: "+1 555-0110",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa",
    department: "Customer Support",
    position: "Support Lead",
    employmentType: "full_time",
    status: "active",
    hireDate: "2021-05-20",
    salary: 58000,
    createdAt: "2021-05-20T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "10",
    employeeId: "EMP010",
    firstName: "Kevin",
    lastName: "Thompson",
    email: "kevin.thompson@hrflow.com",
    phone: "+1 555-0111",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kevin",
    department: "Operations",
    position: "Operations Coordinator",
    employmentType: "part_time",
    status: "inactive",
    hireDate: "2024-01-02",
    salary: 45000,
    createdAt: "2024-01-02T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "11",
    employeeId: "EMP011",
    firstName: "Michelle",
    lastName: "Lee",
    email: "michelle.lee@hrflow.com",
    phone: "+1 555-0112",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michelle",
    department: "Engineering",
    position: "Junior Developer",
    employmentType: "full_time",
    status: "active",
    hireDate: "2023-08-14",
    salary: 68000,
    managerId: "5",
    createdAt: "2023-08-14T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "12",
    employeeId: "EMP012",
    firstName: "Christopher",
    lastName: "Davis",
    email: "christopher.davis@hrflow.com",
    phone: "+1 555-0113",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Christopher",
    department: "Finance",
    position: "Accountant",
    employmentType: "full_time",
    status: "active",
    hireDate: "2022-03-07",
    salary: 67000,
    createdAt: "2022-03-07T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
];

const today = new Date().toISOString().split("T")[0];

export const mockAttendanceRecords: AttendanceRecord[] = [
  { id: "1", employeeId: "1", date: today, clockIn: "09:02", clockOut: "18:15", status: "present", workHours: 9.2 },
  { id: "2", employeeId: "2", date: today, clockIn: "08:55", clockOut: "17:30", status: "present", workHours: 8.6 },
  { id: "3", employeeId: "3", date: today, clockIn: "09:30", status: "late", workHours: 0 },
  { id: "4", employeeId: "4", date: today, clockIn: "08:45", clockOut: "17:00", status: "present", workHours: 8.25 },
  { id: "5", employeeId: "5", date: today, clockIn: "08:30", clockOut: "19:00", status: "present", workHours: 10.5, overtime: 2.5 },
  { id: "6", employeeId: "6", date: today, status: "on_leave" },
  { id: "7", employeeId: "7", date: today, clockIn: "09:00", clockOut: "18:00", status: "present", workHours: 9 },
  { id: "8", employeeId: "8", date: today, status: "absent" },
  { id: "9", employeeId: "9", date: today, clockIn: "08:58", clockOut: "17:45", status: "present", workHours: 8.8 },
  { id: "10", employeeId: "10", date: today, clockIn: "13:00", clockOut: "17:00", status: "half_day", workHours: 4 },
  { id: "11", employeeId: "11", date: today, clockIn: "09:05", status: "present", workHours: 0 },
  { id: "12", employeeId: "12", date: today, clockIn: "08:50", clockOut: "17:30", status: "present", workHours: 8.7 },
];

export const mockLeaveRequests: LeaveRequest[] = [
  {
    id: "1",
    employeeId: "6",
    employeeName: "David Brown",
    type: "annual",
    startDate: "2024-01-20",
    endDate: "2024-01-25",
    days: 5,
    reason: "Family vacation",
    status: "approved",
    approvedBy: "Emily Rodriguez",
    createdAt: "2024-01-10T00:00:00Z",
  },
  {
    id: "2",
    employeeId: "1",
    employeeName: "Sarah Johnson",
    type: "sick",
    startDate: "2024-01-28",
    endDate: "2024-01-29",
    days: 2,
    reason: "Doctor appointment",
    status: "pending",
    createdAt: "2024-01-22T00:00:00Z",
  },
  {
    id: "3",
    employeeId: "8",
    employeeName: "Robert Garcia",
    type: "personal",
    startDate: "2024-02-01",
    endDate: "2024-02-01",
    days: 1,
    reason: "Personal matter",
    status: "pending",
    createdAt: "2024-01-23T00:00:00Z",
  },
  {
    id: "4",
    employeeId: "4",
    employeeName: "James Williams",
    type: "annual",
    startDate: "2024-01-15",
    endDate: "2024-01-15",
    days: 1,
    reason: "Moving day",
    status: "rejected",
    createdAt: "2024-01-08T00:00:00Z",
  },
];

export const mockPayrollRecords: PayrollRecord[] = mockEmployees.map((emp, index) => ({
  id: `payroll-${index + 1}`,
  employeeId: emp.id,
  employee: emp,
  period: `${new Date().toLocaleString('default', { month: 'long' })} ${new Date().getFullYear()}`,
  month: new Date().toLocaleString('default', { month: 'long' }),
  year: new Date().getFullYear(),
  basicSalary: emp.salary / 12,
  allowances: Math.random() > 0.7 ? Math.floor(Math.random() * 500) : 0,
  deductions: Math.floor((emp.salary / 12) * 0.05),
  netPay: Math.floor((emp.salary / 12) * 0.95),
  status: index < 3 ? "paid" : index < 6 ? "processed" : "pending",
  paidAt: index < 3 ? "2024-01-25T00:00:00Z" : undefined,
  processedAt: index < 6 ? "2024-01-20T00:00:00Z" : undefined,
}));

export const mockDashboardStats: DashboardStats = {
  totalEmployees: mockEmployees.length,
  presentToday: mockAttendanceRecords.filter((a) => a.status === "present").length,
  onLeave: mockAttendanceRecords.filter((a) => a.status === "on_leave").length,
  pendingLeaveRequests: mockLeaveRequests.filter((l) => l.status === "pending").length,
  absentToday: mockAttendanceRecords.filter((a) => a.status === "absent").length,
  lateToday: mockAttendanceRecords.filter((a) => a.status === "late").length,
  totalDepartments: new Set(mockEmployees.map((e) => e.department)).size,
  newEmployeesThisMonth: mockEmployees.filter((e) => e.hireDate.startsWith("2024-01")).length,
};

export const mockAttendanceTrend: AttendanceTrend[] = Array.from({ length: 7 }, (_, i) => {
  const date = new Date();
  date.setDate(date.getDate() - (6 - i));
  return {
    date: date.toISOString().split("T")[0],
    present: Math.floor(Math.random() * 3) + 9,
    absent: Math.floor(Math.random() * 2),
    late: Math.floor(Math.random() * 2),
  };
});

export const mockDepartmentDistribution: DepartmentDistribution[] = [
  { department: "Engineering", count: 3, percentage: 25 },
  { department: "Sales", count: 2, percentage: 16.7 },
  { department: "Finance", count: 2, percentage: 16.7 },
  { department: "Human Resources", count: 1, percentage: 8.3 },
  { department: "Marketing", count: 1, percentage: 8.3 },
  { department: "Design", count: 1, percentage: 8.3 },
  { department: "Customer Support", count: 1, percentage: 8.3 },
  { department: "Operations", count: 1, percentage: 8.3 },
];

export const mockRecentActivity: RecentActivity[] = [
  { id: "1", type: "attendance", message: "Sarah Johnson clocked in at 09:02", timestamp: new Date().toISOString(), employeeName: "Sarah Johnson" },
  { id: "2", type: "leave", message: "New leave request from Robert Garcia", timestamp: new Date(Date.now() - 3600000).toISOString(), employeeName: "Robert Garcia" },
  { id: "3", type: "payroll", message: "January payroll processing completed", timestamp: new Date(Date.now() - 7200000).toISOString() },
  { id: "4", type: "employee", message: "Kevin Thompson completed onboarding", timestamp: new Date(Date.now() - 86400000).toISOString(), employeeName: "Kevin Thompson" },
  { id: "5", type: "attendance", message: "David Brown marked as on leave", timestamp: new Date(Date.now() - 172800000).toISOString(), employeeName: "David Brown" },
];
